[workspace]
resolver = "2"
members = [
    # Databases
    "lib/databases/sqlite",

    # Library stuff
    "lib/spec"
]


[package]
name = "policy-store"
version = "0.1.0"
edition = "2021"
authors = ["Bas Kloosterman", "Daniel Voogsgerd", "Tim Müller"]
repository.workspace = true
license.workspace = true
description = "Stores policy for use with a policy reasoner."


[workspace.package]
repository = "https://github.com/epi-project/policy-store"
license = "Apache-2.0"


[dependencies]
sqlite-database = { path = "lib/databases/sqlite", optional = true }
specifications = { path = "lib/spec" }


[features]
default = []

databases = ["sqlite-database"]
sqlite-database = ["dep:sqlite-database"]
