name: Cargo Clippy

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      rust-version:
        required: false
        type: string

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  cargo-clippy:
    name: "${{ inputs.os }} / ${{ inputs.rust-version }}"
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Override active rustup toolchain
        if: inputs.rust-version != ''
        run: echo "RUSTUP_TOOLCHAIN=${{ inputs.rust-version }}" >> $GITHUB_ENV

      - name: Show toolchain
        run: rustup show active-toolchain

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run clippy
        run: cargo clippy --workspace
